FROM paddleocr:cuda9.0-cudnn7

ARG service_home="/opt/PaddleOCR"
# 测试用
# ARG det_model_url="https://paddleocr.bj.bcebos.com/20-09-22/mobile/det/ch_ppocr_mobile_v1.1_det_infer.tar"
# ARG rec_model_url="https://paddleocr.bj.bcebos.com/20-09-22/mobile/rec/ch_ppocr_mobile_v1.1_rec_infer.tar"
# ARG cls_model_url="https://paddleocr.bj.bcebos.com/20-09-22/cls/ch_ppocr_mobile_v1.1_cls_infer.tar"

ARG det_model_url="https://paddleocr.bj.bcebos.com/20-09-22/server/det/ch_ppocr_server_v1.1_det_train.tar"
ARG rec_model_url="https://paddleocr.bj.bcebos.com/20-09-22/server/rec/ch_ppocr_server_v1.1_rec_pre.tar"
ARG cls_model_url="https://paddleocr.bj.bcebos.com/20-09-22/cls/ch_ppocr_mobile_v1.1_cls_train.tar"


ARG pypi_mirror_url="https://mirror.baidu.com/pypi/simple"
ARG volume_dir="/opt/PaddleOCR/ocr-files"
ARG git_url="https://github.com.cnpmjs.org/JhihJian/PaddleOCR.git"
# Clone repo
RUN mkdir "$service_home" \
    && git -c http.sslVerify=false clone "$git_url" "$service_home" \
    && cd "$service_home" 

# Download Model
RUN cd "$service_home" \
&& mkdir "inference" && cd "inference" \
&& wget "$det_model_url" -O "det_model.tar" && mkdir "det_model" && tar xf "det_model.tar" -C "det_model" && mv det_model/*/* det_model \
&& wget "$rec_model_url" -O "rec_model.tar" && mkdir "rec_model" && tar xf "rec_model.tar" -C "rec_model" && mv rec_model/*/* rec_model \
&& wget "$cls_model_url" -O "cls_model.tar" && mkdir "cls_model" && tar xf "cls_model.tar" -C "cls_model" && mv cls_model/*/* cls_model \
&& cd ..

# Install Dependences
RUN cd "$service_home" \
&& python3 -m pip install --upgrade pip \
&& python3 -m pip install paddlepaddle==2.0.0b0 -i "$pypi_mirror_url" \
&& python3 -m pip install -r requirements.txt -i  "$pypi_mirror_url" 

# Run Application
# cd "/opt/PaddleOCR" && python3 ocr_main.py
# 指定监听端口
EXPOSE 9111

VOLUME "$volume_dir"

# docker build -t paddleocr-jj:1.0.0 -f dockerFile .
#  docker run --name jjocr -v /opt/ocr-docker/ocr-files:/opt/PaddleOCR/ocr-files --network=host -it paddleocr-jj:1.0.0 /bin/bash
# python3 /opt/PaddleOCR/tools/infer/predict_system.py --image_dir="./doc/imgs/11.jpg" --det_model_dir="./inference/det_model/"  --rec_model_dir="./inference/rec_model/" --cls_model_dir="./inference/cls_model/" --use_angle_cls=True --use_space_char=True
# ctrl+P+Q可退出docker 重新进入 docker container exec -it jjocr /bin/bash

