FROM centos/python-38-centos7:latest

ARG pypi_mirror_url="https://mirror.baidu.com/pypi/simple"
ARG service_home="/opt/Bilibili-Video-Extract"
ARG volume_dir="/opt/ocr-files/"
ARG git_url="https://github.com.cnpmjs.org/JhihJian/Bilibili-Video-Extract.git"

# 如果不加这个，会导致权限不够，无法创建文件夹
USER root

# install ffmpeg
RUN yum install dnf epel-release -y \
&& dnf install --nogpgcheck https://download1.rpmfusion.org/free/el/rpmfusion-free-release-7.noarch.rpm https://download1.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-7.noarch.rpm -y \
&& dnf install http://rpmfind.net/linux/epel/7/x86_64/Packages/s/SDL2-2.0.10-1.el7.x86_64.rpm -y \
&& dnf install ffmpeg ffmpeg-devel -y

# Clone repo
RUN mkdir "$service_home" \
    && git -c http.sslVerify=false clone "$git_url" "$service_home" \
    && cd "$service_home" 

# Install Dependences
RUN cd "$service_home" \
&& python3 -m pip install --upgrade pip \
&& python3 -m pip install -r requirements.txt -i  "$pypi_mirror_url" 

RUN mkdir -p "$volume_dir"
VOLUME "$volume_dir"

# docker build -t bili-extract:1.0.0 -f dockerFile .
# docker run --name bili -v /opt/video_download:/opt/video_download --network=host -it bili-extract:1.0.0 /bin/bash
# ctrl+P+Q可退出docker  
# 重新进入 docker container exec -it bili /bin/bash



